### ISSUE TITLE
桌面版自带的官方服务在点击登录后没有关闭的按钮

### ISSUE THREAD

**Issue by libashanxi** [Privoce/vocechat-desktop#3]
![image](https://github.com/Privoce/vocechat-desktop/assets/65264574/a890863a-6c03-4d03-9f55-f5350003e7c1)
桌面版自带的服务器，未登录状态下，但是在我点击发言登录后，就进入了登录注册页面，假如我现在不想注册，就想访客看看，此时没有关闭登录注册页面的按钮，也回不到之前未点登录时的公共聊天页面了

**Comment by libashanxi** [comment]
以上情况不局限于以上说的，还存在与比如我不小心点了github登录，但是我假如没有github账号，我想换一个方式登录，此时也没有退出的按钮
![image](https://github.com/Privoce/vocechat-desktop/assets/65264574/2909db14-47a3-4636-a538-6e910dfc53a1)

**Comment by zerosoul** [comment]
可以试试最新版  底部加了几个快捷操作  
![image](https://github.com/Privoce/vocechat-desktop/assets/2985895/0e7d8215-5b4e-484b-b270-b9052d4a7ac2)
